"""Stage2 tests generated by AGY; assertions tightened during Codex review."""
import hashlib
import json
import pytest
from vmv.script import confirm_script, prepare_script


def test_prepare_script_chinese_multiline_crlf_preserved(tmp_path):
    source_text = "第一段第一行内容\r\n第一段第二行内容\r\n\r\n第二段独行文本\r\n\r\n第三段首行\n第三段次行延续"
    source_file = tmp_path / 'source.txt'
    source_file.write_bytes(source_text.encode('utf-8'))
    out = tmp_path / 'draft'
    prepare_script(source_file, out)
    data = json.loads((out / 'segments.json').read_text())
    assert data['source_text'] == source_text
    assert data['source_sha256'] == hashlib.sha256(source_text.encode()).hexdigest()
    assert data['state'] == 'draft'
    assert data['sample'] is False
    assert [s['id'] for s in data['segments']] == ['seg-001', 'seg-002', 'seg-003']
    assert [s['narration'] for s in data['segments']] == ['第一段第一行内容\r\n第一段第二行内容', '第二段独行文本', '第三段首行\n第三段次行延续']
    for s in data['segments']:
        assert source_text[s['start']:s['end']] == s['narration']
        assert s['status'] == 'needs_review'
        assert s['visual_requirement'] == '测试生成内容'


@pytest.mark.parametrize('raw,error', [(b'', ValueError), (b'\xff\xfe', UnicodeDecodeError)])
def test_prepare_invalid_source(tmp_path, raw, error):
    source = tmp_path / 'source.txt'
    source.write_bytes(raw)
    with pytest.raises(error):
        prepare_script(source, tmp_path / 'out')
    assert not (tmp_path / 'out').exists()


def test_prepare_sample_and_html_injection(tmp_path):
    source = tmp_path / 'sample.txt'
    source.write_text("<script>alert('xss')</script>\n\n<img src=x onerror=alert(1)>")
    out = tmp_path / 'out'
    prepare_script(source, out, sample=True)
    data = json.loads((out / 'segments.json').read_text())
    html = (out / 'summary.html').read_text()
    assert data['sample'] is True
    assert "<script>alert('xss')</script>" not in html
    assert '<img src=x onerror=alert(1)>' not in html
    assert '&lt;script&gt;' in html
    assert '合成测试稿' in html


def fixture_draft(tmp_path):
    source = tmp_path / 'source.txt'
    source.write_text('第一幕：开场旁白。\n\n第二幕：高潮冲突。')
    out = tmp_path / 'draft'
    prepare_script(source, out)
    draft = json.loads((out / 'segments.json').read_text())
    requirements = {'source_sha256': draft['source_sha256'], 'segments': [
        {**s, 'characters': '人物甲', 'setting': '场景甲', 'action': '动作甲',
         'emotion': '情绪甲', 'visual_requirement': '人物坐姿近景', 'status': 'confirmed'}
        for s in draft['segments']]}
    return out / 'segments.json', draft, requirements


def test_confirm_roundtrip(tmp_path):
    path, draft, requirements = fixture_draft(tmp_path)
    req = tmp_path / 'requirements.json'
    req.write_text(json.dumps(requirements, ensure_ascii=False))
    out = tmp_path / 'confirmed'
    confirm_script(path, req, out)
    result = json.loads((out / 'segments.json').read_text())
    assert result['state'] == 'confirmed'
    assert result['source_text'] == draft['source_text']
    assert [s['visual_requirement'] for s in result['segments']] == ['人物坐姿近景', '人物坐姿近景']
    assert all(s['status'] == 'confirmed' for s in result['segments'])


@pytest.mark.parametrize('case', ['hash', 'draft_hash', 'offset', 'duplicate', 'missing', 'unknown', 'order', 'text', 'type', 'empty', 'unconfirmed', 'draft_root', 'req_root', 'segment_type', 'offset_bool', 'req_offset_type', 'req_offset_bool', 'req_offset_value', 'sample_type', 'sample_mismatch'])
def test_confirm_tampering_rejected(tmp_path, case):
    path, draft, req = fixture_draft(tmp_path)
    if case == 'hash': req['source_sha256'] = 'a'*64
    elif case == 'draft_hash': draft['source_sha256'] = 'b'*64
    elif case == 'offset': draft['segments'][0]['start'] = 9999
    elif case == 'duplicate': req['segments'][1]['id'] = 'seg-001'
    elif case == 'missing': req['segments'].pop()
    elif case == 'unknown': req['segments'][0]['id'] = 'seg-999'
    elif case == 'order': req['segments'].reverse()
    elif case == 'text': req['segments'][0]['narration'] = '篡改后的文本'
    elif case == 'type': req['segments'][0]['characters'] = 100
    elif case == 'empty': req['segments'][0]['visual_requirement'] = '  \t\n'
    elif case == 'unconfirmed': req['segments'][0]['status'] = 'needs_review'
    elif case == 'draft_root': draft = []
    elif case == 'req_root': req = None
    elif case == 'segment_type': draft['segments'][0] = []
    elif case == 'offset_bool': draft['segments'][0]['start'] = False
    elif case == 'req_offset_type': req['segments'][0]['start'] = 'bad'
    elif case == 'req_offset_bool': req['segments'][0]['start'] = False
    elif case == 'req_offset_value': req['segments'][0]['end'] = 9999
    elif case == 'sample_type': req['sample'] = 0
    elif case == 'sample_mismatch': req['sample'] = True
    path.write_text(json.dumps(draft, ensure_ascii=False))
    req_path = tmp_path / 'requirements.json'
    req_path.write_text(json.dumps(req, ensure_ascii=False))
    with pytest.raises(ValueError):
        confirm_script(path, req_path, tmp_path / 'confirmed')
    assert not (tmp_path / 'confirmed').exists()


def test_existing_output_protected(tmp_path):
    source = tmp_path / 'source.txt'
    source.write_text('正常文本段落')
    out = tmp_path / 'existing'
    out.mkdir()
    sentinel = out / 'keep.txt'
    sentinel.write_text('保留')
    with pytest.raises((FileExistsError, ValueError)):
        prepare_script(source, out)
    assert sentinel.read_text() == '保留'


@pytest.fixture(autouse=True)
def offline_generation(monkeypatch):
    from vmv import script_generation
    def generate(segments):
        return [{key: '测试生成内容' for key in ('characters', 'setting', 'action', 'emotion', 'visual_requirement')} for segment in segments]
    monkeypatch.setattr(script_generation, 'generate_requirements', generate)
